#!/bin/bash

mkdir HL1-8_trimmed

curl -L https://figshare.com/ndownloader/files/40074535 -o HL1-8_trimmed/HL1_R1_paired.fastq.gz
curl -L https://figshare.com/ndownloader/files/40074532 -o HL1-8_trimmed/HL1_R2_paired.fastq.gz
