#!/bin/bash
set -e

# downloading kofamscan db
wget ftp://ftp.genome.jp/pub/db/kofam/ko_list.gz
gunzip ko_list.gz

# curl -LO https://www.genome.jp/ftp/db/kofam/profiles.tar.gz
# tar -xvf profiles.tar.gz
